### PR TITLE
✨ Add support for get_template_from_string()

### LINKED ISSUE #1: feature request: to support get_template_from_string()
a new interface is required from https://github.com/moremoban/moban/issues/154

### PR DESCRIPTION
**Pull request by CLiu13**
With this addition, moban-slim will be compatible with 0.3.8.
Also accepts extensions in the engine constructor.

Closes https://github.com/moremoban/moban-slim/issues/1

EDIT (06/16/2020): This also addresses https://github.com/moremoban/moban-slim/issues/3, https://github.com/moremoban/moban-slim/issues/5, and https://github.com/moremoban/moban-slim/issues/6.

### CODE REVIEW

**Comment by chfw** [comment]
ImportError: No module named 'uncompyle6'  <--

**Comment by chfw** [comment]
by the way, as collaborator, you do not need to fork it to send PR.

**Comment by CLiu13** [comment]
> ImportError: No module named 'uncompyle6' <--

Yeah, my updated version of slimish-jinja2 for Python 3 requires it as a dependency, which I listed under the `requirements.txt` of it - however, currently working on getting an official updated version of slimish-jinja2 released.

UPDATE: Owner of slimish-jinja2 says that an updated version of it will be released on PyPi tomorrow.

**Comment by chfw** [comment]
please look at the build error. it is now genuine.

**Comment by CLiu13** [comment]
> please look at the build error. it is now genuine.

I have modified the test case so that it passes, but I no longer attempt to pass an entire slimish-jinja template in string form, because it simply doesn't make sense - [those templates are multiline files](https://github.com/thoughtnirvana/slimish-jinja2/blob/master/demo.slim), and I doubt anyone will try to input them via the command line (if it even is possible). However, with the modified test case, I still verify that the `get_string_template()` method works properly with Jinja2.

EDIT: A previous test case that worked before also broke for some apparent reason (not related to my changes). I have corrected it.

**Comment by CLiu13** [comment]
With the [latest release of slimish-jinja](https://pypi.org/project/slimish-jinja/1.1.0/) supporting Python 3, I have updated the requirements to use the official version of it.

EDIT: Fixing upstream issues with slimish-jinja2, Travis should be green after those are addressed.

**Comment by chfw** [comment]
python 2.7 failed.

and please update change log.

**Comment by CLiu13** [comment]
> python 2.7 failed.

It is an issue upstream with slimish-jinja2 - currently working with the owner of it on finding a solution.

**Comment by chfw** [comment]
@CLiu13 any progress?

**Comment by CLiu13** [comment]
The maintainer of slimish-jinja2 has not responded to my issue. Repo seems abandoned for the time being - last update was 6 months ago. I will see what I can do about it.

**Comment by chfw** [comment]
any update in 2020 :)?

**Comment by CLiu13** [comment]
Looking into it again! Will provide an update within the next few days :)

**Comment by CLiu13** [comment]
@chfw Everything should be good to go now (hopefully)! Had to update the project to match the latest version of moban since it has been a while.

**Comment by CLiu13** [comment]
Commenting here for visibility: ```EDIT (06/16/2020): This also addresses issues #3, #5, and #6.```
(see [original PR comment](https://github.com/moremoban/moban-slim/pull/4#issue-246089692) for the edit)

**Comment by chfw** [comment]
Excellent job!

Now here are the extra milage if you would like to go. I appreciate that it has already took you a lot of time and effort. 

Would you like to add two more class attributes? Like the following one:

https://github.com/moremoban/moban-handlebars/blob/dev/moban_handlebars/engine.py#L35

it would give a personalized action text when moban invoke moban-slim.

And would you like to offer a quick start example to showcase the library? again, like this one:

https://github.com/moremoban/moban-handlebars/blob/dev/.moban.d/handlebars_example.rst.jj2

With above doc, I can insert it into moban's main Readme: https://github.com/moremoban/moban/blob/dev/.moban.d/moban_readme.jj2#L191

**Comment by CLiu13** [comment]
Done 👍

**Review by chfw — APPROVED** [review]
Bravo!

**Pull request merged**
