### PR TITLE
release 0.0.2

### PR DESCRIPTION
**Pull request by chfw**
delivers #1, #3, #5, #6

### CODE REVIEW

**Review by CLiu13 — APPROVED** [review]
LGTM 👍

**Comment by chfw** [comment]
will ship it!

**Comment by chfw** [comment]
@CLiu13 , for your information, each release made on github will trigger a pypi package publish action. https://github.com/moremoban/moban-slim/actions/runs/137712399. so in the future, you can also do the release as you are an admin for this repo.

**Comment by CLiu13** [comment]
Ah ok, sounds good - thanks!

**Pull request merged**
